import { Platform, StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import { Height, WIDTH } from '../../../config/constants';

const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    width: WIDTH,
    backgroundColor: '#00838F',
    alignSelf: 'stretch',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: Platform.OS === 'ios' ? 0 : 40,
  },
  headerTitle: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '500',
    marginVertical: 10,
  },
  topBanner: {
    backgroundColor: '#F5F5F540',
    paddingVertical: 10,
    paddingHorizontal: 6,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  topBannerText: {
    fontSize: 14,
    color: '#757575',
    lineHeight: 16,
  },
  superscript: {
    position: 'relative',
    top: -3,
    fontSize: 10,
  },
  imageContainer: {
    marginTop: 10,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '500',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 20,
    marginHorizontal: 20,
  },
  contentRow: {
    marginTop: Platform.OS === 'ios' ? 10 : 0,
    alignSelf: 'stretch',
    marginHorizontal: 20,
    backgroundColor: '#37BECA10',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginBottom: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentText: {
    fontSize: 14,
    color: '#757575',
  },
  footer: {
    marginTop: 200,
    paddingRight: 10,
    marginBottom: 50,
  },
  footerRow: {
    flexDirection: 'row',
  },
  footerLeftCol: {
    fontSize: 12,
    color: '#616161',
  },
  footerRightCol: {
    fontSize: 12,
    color: '#616161',
    marginLeft: 4,
  },
  buttonContainer: {
    backgroundColor: '#ffffff',
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingBottom: 200,
    paddingTop: 10,
  },
  buttonInfoText: {
    textAlign: 'center',
    marginBottom: 5,
    color: '#656565',
  },
  documentItemContainer: {
    height: 60,
    marginHorizontal: 10,
    alignSelf: 'stretch',
    marginVertical: 4,
    borderWidth: Platform.OS === 'ios' ? 0.1 : 0,
    justifyContent: 'center',
    shadowColor: 'rgba(0,0,0,0.12)',
    borderRadius: 12,
    shadowOffset: {
      width: -4,
      height: 5,
    },
  },
  documentItemView: {
    height: 60,
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    paddingLeft: 5,
    paddingRight: 10,
    paddingVertical: 15,
  },

  documentItemMainView: {
    flex: 1,
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },

  documentItemRadioButtonView: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  radioButtonFirstCircle: {
    height: 16,
    width: 16,
    borderWidth: 1,
    borderRadius: 100,
    borderColor: '#027580',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonSecondCircle: {
    height: 9,
    width: 9,
    borderRadius: 50,
    backgroundColor: '#027580',
  },
  radioUnselected: {
    height: 16,
    width: 16,
    borderWidth: 1,
    borderRadius: 100,
    borderColor: '#9E9E9E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  documentContentView: {
    flex: 4,
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  documentNameStyle: {
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: '#000000',
  },

  safeAreaView: {
    flex: 1,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  mainView: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Platform.OS === 'ios' ? 0 : 40,
    marginBottom: 10,
  },
  backButtonStyle: {
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  helpTextStyle: {
    fontWeight: '400',
    fontSize: RFValue(16, 812),
    color: '#000000',
  },
  progressBarContainer: {
    width: WIDTH - 40,
    marginBottom: 10,
  },

  contentContainer: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  scrollViewStyles: {
    alignSelf: 'center',
    width: WIDTH - 40,
  },
  confirmIdentityText: {
    fontWeight: '500',
    fontSize: 25,
    color: '#000000',
    textAlign: 'left',
    marginTop: 10,
  },
  selectDocumentTextStyle: {
    fontWeight: '400',
    fontSize: 16,
    color: '#000000',
    textAlign: 'left',
    marginLeft: 10,
    marginTop: 40,
  },
  documentViewContainer: {
    flex: 1,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  documentGroupButtonView: {
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 30,
  },

  documentRequirementView: {
    alignSelf: 'stretch',
    backgroundColor: '#F5F5F535',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    paddingVertical: 20,
    marginTop: 10,
  },
  documentRequirementTitleView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  documentRequirementTitleStyle: {
    color: '#616161',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 24,
  },
  bulletView: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    marginTop: 25,
  },
  bulletContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bulletStyle: {
    height: 25,
    width: 25,
    borderRadius: 50,
    backgroundColor: '#EEEEEE',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
  },
  bulletNumberStyle: {
    fontWeight: '400',
    fontSize: 11,
    color: '#5A5858',
  },
  requirementTextContentStyle: {
    fontWeight: '400',
    fontSize: 14,
    color: '#616161',
    textAlign: 'left',
    marginLeft: 10,
    marginRight: 30,
  },
  helpTextContainer: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: Platform.OS === 'ios' ? 10 : 20,
  },
  ctaHelpTextStyle: {
    marginLeft: 5,
    fontWeight: '400',
    fontSize: 14,
    color: '#BDBDBD',
  },
  imageContainerStyle: {
    height: Height / 1.5,
    width: WIDTH - 100,
    borderRadius: 30,
    backgroundColor: '#D9D9D9',
    justifyContent: 'center',
  },
  imageView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  imageStyle: {
    borderRadius: 27,
    alignSelf: 'center',
    resizeMode: 'cover',
    height: Height / 2,
    width: WIDTH - 170,
  },
  imagePreviewMainView: {
    flex: 1,
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 30,
  },
  ctasContainer: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
export default styles;
